config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"
  resources :users, only: [:new,:create]
  resource :session, only: [:new, :create, :destroy]
  namespace :api, defaults: {format: :json} do
    resources :restaurants, only: [:index, :create, :update, :show]
    resources :reviews, only: [:index, :create, :show, :update, :destroy]
    resources :tags, only: [:index, :create, :show]
    resources :user, only: [:show, :update]
    resources :locations, only: [:index, :create, :show,:update]
  end
  get 'guest' => 'sessions#guest_log_in'
end
          

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  image_url       :string           default("https://res.cloudinary.com/dnifqmdlf/image/upload/v1444929813/images_ohgzbq.png")
#

class User < ActiveRecord::Base
  attr_reader :password, :password_confirm

  validates :username, :session_token, uniqueness: true
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  has_many :reviews

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && BCrypt::Password.new(user.password_digest).is_password?(password)
    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
   self.session_token = SecureRandom.urlsafe_base64(16)
   self.save!
   self.session_token
  end

  def password_confirm=(password)
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/api/user_controller.rb
class Api::UserController < ApplicationController
  def show
    @user = User.where(id: params[:id]).includes(reviews: {restaurant: :pictures})[0]
    render :show
  end


  def update
    if params[:id].to_i != current_user.id
      @user = User.new
      render :show, status: 404
    else
      @user = User.find(params[:id])
      if @user.update(user_params)
        @user = User.where(id: params[:id]).includes(reviews: {restaurant: :pictures})[0]
        render :show
      else
        flash[:errors] = @user.errors.full_messages
        render :show, status: 422
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:image_url, :bookMark)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_to_root, only: [:new]
  def new
    @user = User.new
    render :new
  end

  def create
    
    if (user_params[:password] == user_params[:password_confirm])
      @user = User.new(user_params)
      if @user.save
        sign_in(@user)
        redirect_to root_url
      else
        flash.now[:errors] = @user.errors.full_messages
        render:new
      end
    else
      flash.now[:errors] = ["Passwords do not match!"]
      @user = User.new(user_params)
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirm)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="home"><a class="home-link" href="/#">Omnomnom</a></div>

<div class="sign group">
  <div class="sign-form">
      <h1>Sign Up for Omnomnom</h1>
        <p id="guest">Or log in as a <%= link_to 'Guest', guest_path%>!</p>
        <form class="sign-form-fields" action="/users" method="post">
          <%= auth_token %>
          <label> Username
            <input type="text" class="form-control" name="user[username]" value="<%= @user.username %>">
          </label>
          <br>
          <label> Password
            <input type="password" class="form-control" name="user[password]" value="">
          </label>
          <br>
          <label> Password Confirmation
            <input type="password" class="form-control" name="user[password_confirm]" value="">
          </label>
          <br>
          <input class="form-control sign-submit" type="submit" value="Sign Up!">
        </form>
      <p id="guest">Already with omnom? <a href="<%= new_session_url %>">Log in</a></p>
  </div>
  <div class="image">
    <img src="https://res.cloudinary.com/omnombloop/image/upload/v1445931029/signup_illustration_bze0or.png"></img>
  </div>
</div>